# Generated by Django 3.0.5 on 2021-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите имя сделки', verbose_name='имя сделки')),
                ('email_from', models.EmailField(max_length=254)),
                ('partner_name', models.TextField(help_text='Введите имя заказчика', verbose_name='имя заказчика')),
            ],
        ),
    ]
