# Generated by Django 3.0.5 on 2021-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbform',
            name='partner_name',
            field=models.CharField(help_text='Введите имя заказчика', max_length=250, verbose_name='имя заказчика'),
        ),
        migrations.AlterField(
            model_name='fbform',
            name='text',
            field=models.CharField(help_text='Введите имя сделки', max_length=250, verbose_name='имя сделки'),
        ),
    ]
